# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    concurrency:
      group: ci-main-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,nodefaults
        channel-priority: true
        activate-environment: kaleidoscope
        environment-file: conda/dev-linux-64.yaml

    - name: build
      run: make build-with-tests CLEAN=1

    - name: run example tests
      run: make test-examples

    - name: lint
      run: |
        pre-commit install
        pre-commit run --all-files
